GET https://api.dev.package-search.services.jetbrains.com/package-info-by-id-hashes
Accept: application/json
Content-Type: application/json

{"ids":["64c3a4ec52a87e2619c4cd6f730523c696ed69506cd245e2cc9348e0f0d25633","b1593db63e14fb2a7452eef250611a34b8c867b201b18edfe8132e3ba2d1cb91","9a69143550d8e605be3c2c9d3422398070775de636a6fb390c1312f400b84276","1c0c7ca7b0cd84f408399ae7cd71b380a930a8deb90ca7c731e951d79769314b","bf0832dafd81a3725cfad2bf88ea0838cc0089e381ffdba6d129eeb2bf166cb8","d23c99002a9b23e1679fbbdd4ee118c602dfde18574ea8e6682376117524955d"]}

###
GET https://api.dev.package-search.services.jetbrains.com/search-packages
Accept: application/json
Content-Type: application/json

{
  "packagesType": [
    {
      "type": "gradle",
      "variants": [
        {
          "attributes": {
            "org.jetbrains.kotlin.platform.type": {
              "type": "exactMatch",
              "value": "native"
            },
            "org.jetbrains.kotlin.native.target": {
              "type": "exactMatch",
              "value": "ios_arm64"
            },
            "org.gradle.category": {
              "type": "exactMatch",
              "value": "library"
            },
            "org.gradle.usage": {
              "type": "exactMatch",
              "value": "kotlin-api"
            }
          },
          "mustBeWithFiles": false
        },
        {
          "attributes": {
            "org.jetbrains.kotlin.platform.type": {
              "type": "exactMatch",
              "value": "native"
            },
            "org.jetbrains.kotlin.native.target": {
              "type": "exactMatch",
              "value": "ios_x64"
            },
            "org.gradle.category": {
              "type": "exactMatch",
              "value": "library"
            },
            "org.gradle.usage": {
              "type": "exactMatch",
              "value": "kotlin-api"
            }
          },
          "mustBeWithFiles": false
        },
        {
          "attributes": {
            "org.jetbrains.kotlin.platform.type": {
              "type": "exactMatch",
              "value": "native"
            },
            "org.jetbrains.kotlin.native.target": {
              "type": "exactMatch",
              "value": "tvos_arm64"
            },
            "org.gradle.category": {
              "type": "exactMatch",
              "value": "library"
            },
            "org.gradle.usage": {
              "type": "exactMatch",
              "value": "kotlin-api"
            }
          },
          "mustBeWithFiles": false
        },
        {
          "attributes": {
            "org.jetbrains.kotlin.platform.type": {
              "type": "exactMatch",
              "value": "native"
            },
            "org.jetbrains.kotlin.native.target": {
              "type": "exactMatch",
              "value": "tvos_x64"
            },
            "org.gradle.category": {
              "type": "exactMatch",
              "value": "library"
            },
            "org.gradle.usage": {
              "type": "exactMatch",
              "value": "kotlin-api"
            }
          },
          "mustBeWithFiles": false
        },
        {
          "attributes": {
            "org.jetbrains.kotlin.platform.type": {
              "type": "exactMatch",
              "value": "jvm"
            },
            "org.gradle.category": {
              "type": "exactMatch",
              "value": "library"
            },
            "org.gradle.usage": {
              "type": "exactMatch",
              "value": "java-api"
            },
            "org.gradle.libraryelements": {
              "type": "exactMatch",
              "value": "jar"
            }
          },
          "mustBeWithFiles": false
        },
        {
          "attributes": {
            "org.jetbrains.kotlin.platform.type": {
              "type": "exactMatch",
              "value": "jvm"
            },
            "org.gradle.category": {
              "type": "exactMatch",
              "value": "library"
            },
            "org.gradle.usage": {
              "type": "exactMatch",
              "value": "java-runtime"
            },
            "org.gradle.libraryelements": {
              "type": "exactMatch",
              "value": "jar"
            }
          },
          "mustBeWithFiles": false
        }
      ],
      "mustBeRootPublication": true
    }
  ],
  "searchQuery": "ktor-client-cio"
}

###
GET https://api.dev.package-search.services.jetbrains.com/package-info-by-ids HTTP/2
Content-Type: application/json

{
  "ids": [
    "maven:io.ktor:ktor-client-core"
  ]
}