GET https://api.dev.package-search.services.jetbrains.com/package-info-by-ids
Accept: application/json
Content-Type: application/json

{
    "ids": [
      "maven:io.ktor:ktor-client-cio"
    ]
}

###
GET https://api.dev.package-search.services.jetbrains.com/search-packages
Accept: application/json
Content-Type: application/json

{
  "packagesType": [
    {
      "type": "gradle",
      "mustBeRootPublication": true,
      "variants": []
    }
  ],
  "searchQuery": "ktor-client-cio"
}

###
GET https://api.dev.package-search.services.jetbrains.com/package-info-by-ids HTTP/2
Content-Type: application/json

{
  "ids": [
    "maven:io.ktor:ktor-client-core"
  ]
}