POST https://package-search.services.jetbrains.com/search-packages
Content-Type: application/json

{
  "packagesType": [
    {
      "type": "maven"
    },
    {
      "type": "gradle",
      "variants": [
        {
          "attributes": {
            "org.gradle.usage": {
              "type": "exactMatch",
              "value": "java-runtime"
            },
            "org.gradle.libraryelements": {
              "type": "exactMatch",
              "value": "jar"
            }
          },
          "mustBeWithFiles": false
        }
      ],
      "mustBeRootPublication": true
    }
  ],
  "searchQuery": "kotlinx-datetime"
}