GET http://localhost:8081/api/v3/package-info-by-ids
Accept: application/json
Content-Type: application/json

{
    "ids": [
      "maven:ch.qos.logback:logback-classic"
    ]
}

###
GET http://localhost:8081/api/v3/search-packages
Accept: application/json
Content-Type: application/json

{
  "packagesType": [
    {
      "type": "maven"
    }
  ],
  "searchQuery": "whatever"
}