name: Publish to Marketplace

on:
  release:
    types: [ published ]

jobs:
  publish:
    name: Publish Package Search to Marketplace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - uses: gradle/gradle-build-action@v2
      - name: Run :publishShadowPluginToMarketplace task
        run: ./gradlew publishAllPublicationsToSpaceRepository :plugin:publishPluginToMarketplace
        env:
          MARKETPLACE_TOKEN: ${{ secrets.MARKETPLACE_TOKEN }}
          GRADLE_ENTERPRISE_KEY: ${{ secrets.GRADLE_ENTERPRISE_KEY }}
          SPACE_INTELLIJ_NIGHTLIES_TOKEN: ${{ secrets.SPACE_INTELLIJ_NIGHTLIES_TOKEN }}
          SPACE_INTELLIJ_NIGHTLIES_USERNAME: ${{ secrets.SPACE_INTELLIJ_NIGHTLIES_USERNAME }}
          SPACE_PACKAGE_SEARCH_TOKEN: ${{ secrets.SPACE_PACKAGE_SEARCH_TOKEN }}
          SPACE_PACKAGE_SEARCH_USERNAME: ${{ secrets.SPACE_PACKAGE_SEARCH_USERNAME }}
          CHANGE_NOTES: ${{ github.event.release.body }}
      - name: Run :publishStablePluginToTBE task
        run: ./gradlew :plugin:publishReleasePluginToTBE
        env:
          KMP: true
          TOOLBOX_ENTERPRISE_TOKEN: ${{ secrets.TOOLBOX_ENTERPRISE_TOKEN }}
          GRADLE_ENTERPRISE_KEY: ${{ secrets.GRADLE_ENTERPRISE_KEY }}
          CHANGE_NOTES: ${{ github.event.release.body }}
