name: Publish snapshot to TBE

on:
  push:
    branches: [ master ]

jobs:
  publish:
    name: Publish Package Search Snapshot to TBE
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle
      - uses: gradle/gradle-build-action@v2
      - name: Run :publishShadowPlugin task
        run: ./gradlew :plugin:publishShadowPlugin
        env:
          TOOLBOX_ENTERPRISE_TOKEN: ${{ secrets.TOOLBOX_ENTERPRISE_TOKEN }}
          GRADLE_ENTERPRISE_KEY: ${{ secrets.GRADLE_ENTERPRISE_KEY }}
