name: Run tests

on:
  pull_request:
    branches: [ master ]

jobs:
  gradle:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        gradle-version: [ '5.6.4', '6.9.2', '7.6.4', '8.6' ]
    name: Gradle ${{ matrix.gradle-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    outputs:
      result: ${{ steps.final_step.outputs.result }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: gradle/gradle-build-action@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Run GRADLE tests
        continue-on-error: true
        id: simple-build
        env:
          KMP: true
          GRADLE_VERSION: ${{ matrix.gradle-version }}
          GRADLE_ENTERPRISE_KEY: ${{ secrets.GRADLE_ENTERPRISE_KEY }}
          JAVA_VERSION: ${{matrix.jdk-version}}
          SPACE_INTELLIJ_NIGHTLIES_TOKEN: ${{ secrets.SPACE_INTELLIJ_NIGHTLIES_TOKEN }}
          SPACE_INTELLIJ_NIGHTLIES_USERNAME: ${{ secrets.SPACE_INTELLIJ_NIGHTLIES_USERNAME }}
          SPACE_PACKAGE_SEARCH_TOKEN: ${{ secrets.SPACE_PACKAGE_SEARCH_TOKEN }}
          SPACE_PACKAGE_SEARCH_USERNAME: ${{ secrets.SPACE_PACKAGE_SEARCH_USERNAME }}
        run: ./gradlew :plugin:test --continue --tests "com.jetbrains.packagesearch.plugin.tests.end2end.projectservice.GradleProjectTest"
      - name: Patch IDE config files
        if: steps.simple-build.outcome == 'failure'
        run: kotlinc -script ./.github/workflows/TrustKotlinGradlePluginPatch.main.kts
      - name: Run GRADLE tests PATCHED
        if: steps.simple-build.outcome == 'failure'
        env:
          KMP: true
          GRADLE_VERSION: ${{ matrix.gradle-version }}
          GRADLE_ENTERPRISE_KEY: ${{ secrets.GRADLE_ENTERPRISE_KEY }}
          JAVA_VERSION: ${{matrix.jdk-version}}
          SPACE_INTELLIJ_NIGHTLIES_TOKEN: ${{ secrets.SPACE_INTELLIJ_NIGHTLIES_TOKEN }}
          SPACE_INTELLIJ_NIGHTLIES_USERNAME: ${{ secrets.SPACE_INTELLIJ_NIGHTLIES_USERNAME }}
          SPACE_PACKAGE_SEARCH_TOKEN: ${{ secrets.SPACE_PACKAGE_SEARCH_TOKEN }}
          SPACE_PACKAGE_SEARCH_USERNAME: ${{ secrets.SPACE_PACKAGE_SEARCH_USERNAME }}
        run: ./gradlew :plugin:test --continue --tests "com.jetbrains.packagesearch.plugin.tests.end2end.projectservice.GradleProjectTest"
      - name: Upload test result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: testResult-gradle-${{ matrix.os }}-${{ matrix.gradle-version }}
          path: /home/runner/work/package-search-intellij-plugin/package-search-intellij-plugin/plugin/build/testData
  maven:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    name: Maven on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: gradle/gradle-build-action@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Run MAVEN tests
        id: simple-build
        continue-on-error: true
        env:
          KMP: true
          GRADLE_ENTERPRISE_KEY: ${{ secrets.GRADLE_ENTERPRISE_KEY }}
          JAVA_VERSION: ${{matrix.jdk-version}}
          SPACE_INTELLIJ_NIGHTLIES_TOKEN: ${{ secrets.SPACE_INTELLIJ_NIGHTLIES_TOKEN }}
          SPACE_INTELLIJ_NIGHTLIES_USERNAME: ${{ secrets.SPACE_INTELLIJ_NIGHTLIES_USERNAME }}
          SPACE_PACKAGE_SEARCH_TOKEN: ${{ secrets.SPACE_PACKAGE_SEARCH_TOKEN }}
          SPACE_PACKAGE_SEARCH_USERNAME: ${{ secrets.SPACE_PACKAGE_SEARCH_USERNAME }}
        run: ./gradlew :plugin:test --continue --tests "com.jetbrains.packagesearch.plugin.tests.end2end.projectservice.MavenProjectTest"
      - name: Patch IDE config files
        if: steps.simple-build.outcome == 'failure'
        run: kotlinc -script ./.github/workflows/TrustKotlinGradlePluginPatch.main.kts
      - name: Run MAVEN tests Patched
        if: steps.simple-build.outcome == 'failure'
        env:
          KMP: true
          GRADLE_ENTERPRISE_KEY: ${{ secrets.GRADLE_ENTERPRISE_KEY }}
          JAVA_VERSION: ${{matrix.jdk-version}}
          SPACE_INTELLIJ_NIGHTLIES_TOKEN: ${{ secrets.SPACE_INTELLIJ_NIGHTLIES_TOKEN }}
          SPACE_INTELLIJ_NIGHTLIES_USERNAME: ${{ secrets.SPACE_INTELLIJ_NIGHTLIES_USERNAME }}
          SPACE_PACKAGE_SEARCH_TOKEN: ${{ secrets.SPACE_PACKAGE_SEARCH_TOKEN }}
          SPACE_PACKAGE_SEARCH_USERNAME: ${{ secrets.SPACE_PACKAGE_SEARCH_USERNAME }}
        run: ./gradlew :plugin:test --continue --tests "com.jetbrains.packagesearch.plugin.tests.end2end.projectservice.MavenProjectTest"
      - name: Upload test result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: testResult-maven-${{ matrix.os }}-${{ matrix.gradle-version }}
          path: /home/runner/work/package-search-intellij-plugin/package-search-intellij-plugin/plugin/build/testData
  kmp:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        gradle-version: [ '6.9.2', '7.6.4', '8.6' ]
    name: KMP ${{ matrix.gradle-version }}
    runs-on: ${{ matrix.os }}
    outputs:
      result: ${{ steps.final_step.outputs.result }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: gradle/gradle-build-action@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Run KMP tests
        id: simple-build
        continue-on-error: true
        env:
          KMP: true
          GRADLE_VERSION: ${{ matrix.gradle-version }}
          GRADLE_ENTERPRISE_KEY: ${{ secrets.GRADLE_ENTERPRISE_KEY }}
          JAVA_VERSION: ${{matrix.jdk-version}}
          SPACE_INTELLIJ_NIGHTLIES_TOKEN: ${{ secrets.SPACE_INTELLIJ_NIGHTLIES_TOKEN }}
          SPACE_INTELLIJ_NIGHTLIES_USERNAME: ${{ secrets.SPACE_INTELLIJ_NIGHTLIES_USERNAME }}
          SPACE_PACKAGE_SEARCH_TOKEN: ${{ secrets.SPACE_PACKAGE_SEARCH_TOKEN }}
          SPACE_PACKAGE_SEARCH_USERNAME: ${{ secrets.SPACE_PACKAGE_SEARCH_USERNAME }}
        run: ./gradlew :plugin:test --continue --tests "com.jetbrains.packagesearch.plugin.tests.end2end.projectservice.KMPGradleProjectTest"
      - name: Patch IDE config files
        if: steps.simple-build.outcome == 'failure'
        run: kotlinc -script ./.github/workflows/TrustKotlinGradlePluginPatch.main.kts
      - name: Run KMP tests
        if: steps.simple-build.outcome == 'failure'
        env:
          KMP: true
          GRADLE_VERSION: ${{ matrix.gradle-version }}
          GRADLE_ENTERPRISE_KEY: ${{ secrets.GRADLE_ENTERPRISE_KEY }}
          JAVA_VERSION: ${{matrix.jdk-version}}
          SPACE_INTELLIJ_NIGHTLIES_TOKEN: ${{ secrets.SPACE_INTELLIJ_NIGHTLIES_TOKEN }}
          SPACE_INTELLIJ_NIGHTLIES_USERNAME: ${{ secrets.SPACE_INTELLIJ_NIGHTLIES_USERNAME }}
          SPACE_PACKAGE_SEARCH_TOKEN: ${{ secrets.SPACE_PACKAGE_SEARCH_TOKEN }}
          SPACE_PACKAGE_SEARCH_USERNAME: ${{ secrets.SPACE_PACKAGE_SEARCH_USERNAME }}
        run: ./gradlew :plugin:test --continue --tests "com.jetbrains.packagesearch.plugin.tests.end2end.projectservice.KMPGradleProjectTest"
      - name: Upload test result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: testResult-kmp-gradle-${{ matrix.os }}-${{ matrix.gradle-version }}
          path: /home/runner/work/package-search-intellij-plugin/package-search-intellij-plugin/plugin/build/testData
  version-catalog:
    if: false # Disabled until we make an effort to fix catalogs
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        gradle-version: [ '7.6.4', '8.6' ]
    name: Version Catalog ${{ matrix.gradle-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    outputs:
      result: ${{ steps.final_step.outputs.result }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: gradle/gradle-build-action@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Run VERSION CATALOG tests
        continue-on-error: true
        id: simple-build
        env:
          KMP: true
          GRADLE_VERSION: ${{ matrix.gradle-version }}
          GRADLE_ENTERPRISE_KEY: ${{ secrets.GRADLE_ENTERPRISE_KEY }}
          JAVA_VERSION: ${{matrix.jdk-version}}
          SPACE_INTELLIJ_NIGHTLIES_TOKEN: ${{ secrets.SPACE_INTELLIJ_NIGHTLIES_TOKEN }}
          SPACE_INTELLIJ_NIGHTLIES_USERNAME: ${{ secrets.SPACE_INTELLIJ_NIGHTLIES_USERNAME }}
          SPACE_PACKAGE_SEARCH_TOKEN: ${{ secrets.SPACE_PACKAGE_SEARCH_TOKEN }}
          SPACE_PACKAGE_SEARCH_USERNAME: ${{ secrets.SPACE_PACKAGE_SEARCH_USERNAME }}
        run: ./gradlew :plugin:test --continue --tests "com.jetbrains.packagesearch.plugin.tests.end2end.projectservice.CatalogProjectTest"
      - name: Patch IDE config files
        if: steps.simple-build.outcome == 'failure'
        run: kotlinc -script ./.github/workflows/TrustKotlinGradlePluginPatch.main.kts
      - name: Run VERSION CATALOG tests PATCHED
        if: steps.simple-build.outcome == 'failure'
        env:
          KMP: true
          GRADLE_VERSION: ${{ matrix.gradle-version }}
          GRADLE_ENTERPRISE_KEY: ${{ secrets.GRADLE_ENTERPRISE_KEY }}
          JAVA_VERSION: ${{matrix.jdk-version}}
          SPACE_INTELLIJ_NIGHTLIES_TOKEN: ${{ secrets.SPACE_INTELLIJ_NIGHTLIES_TOKEN }}
          SPACE_INTELLIJ_NIGHTLIES_USERNAME: ${{ secrets.SPACE_INTELLIJ_NIGHTLIES_USERNAME }}
          SPACE_PACKAGE_SEARCH_TOKEN: ${{ secrets.SPACE_PACKAGE_SEARCH_TOKEN }}
          SPACE_PACKAGE_SEARCH_USERNAME: ${{ secrets.SPACE_PACKAGE_SEARCH_USERNAME }}
        run: ./gradlew :plugin:test --continue --tests "com.jetbrains.packagesearch.plugin.tests.end2end.projectservice.CatalogProjectTest"
      - name: Upload test result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: testResult-version-catalog-${{ matrix.os }}-${{ matrix.gradle-version }}
          path: /home/runner/work/package-search-intellij-plugin/package-search-intellij-plugin/plugin/build/testData
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: gradle/gradle-build-action@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Run UNIT tests
        id: simple-build
        continue-on-error: true
        env:
          GRADLE_ENTERPRISE_KEY: ${{ secrets.GRADLE_ENTERPRISE_KEY }}
          SPACE_INTELLIJ_NIGHTLIES_TOKEN: ${{ secrets.SPACE_INTELLIJ_NIGHTLIES_TOKEN }}
          SPACE_INTELLIJ_NIGHTLIES_USERNAME: ${{ secrets.SPACE_INTELLIJ_NIGHTLIES_USERNAME }}
          SPACE_PACKAGE_SEARCH_TOKEN: ${{ secrets.SPACE_PACKAGE_SEARCH_TOKEN }}
          SPACE_PACKAGE_SEARCH_USERNAME: ${{ secrets.SPACE_PACKAGE_SEARCH_USERNAME }}
        run: ./gradlew :plugin:utils:test
      - name: Patch IDE config files
        if: steps.simple-build.outcome == 'failure'
        run: kotlinc -script ./.github/workflows/TrustKotlinGradlePluginPatch.main.kts
      - name: Run UNIT tests
        if: steps.simple-build.outcome == 'failure'
        env:
          GRADLE_ENTERPRISE_KEY: ${{ secrets.GRADLE_ENTERPRISE_KEY }}
          SPACE_INTELLIJ_NIGHTLIES_TOKEN: ${{ secrets.SPACE_INTELLIJ_NIGHTLIES_TOKEN }}
          SPACE_INTELLIJ_NIGHTLIES_USERNAME: ${{ secrets.SPACE_INTELLIJ_NIGHTLIES_USERNAME }}
          SPACE_PACKAGE_SEARCH_TOKEN: ${{ secrets.SPACE_PACKAGE_SEARCH_TOKEN }}
          SPACE_PACKAGE_SEARCH_USERNAME: ${{ secrets.SPACE_PACKAGE_SEARCH_USERNAME }}
        run: ./gradlew :plugin:utils:test
