name: Run tests

on:
  pull_request:
    branches: [ master ]

jobs:
  gradle:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        gradle-version: [ '5.6.4', '6.9.2', '7.6.4', '8.6' ]
    name: Gradle ${{ matrix.gradle-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      MAVEN_SPACE_PASSWORD: ${{ secrets.MAVEN_SPACE_PASSWORD }}
      MAVEN_SPACE_USERNAME: ${{ secrets.MAVEN_SPACE_USERNAME }}
    outputs:
      result: ${{ steps.final_step.outputs.result }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: gradle/gradle-build-action@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Run tests
        env:
          KMP: true
          GRADLE_VERSION: ${{ matrix.gradle-version }}
          GRADLE_ENTERPRISE_KEY: ${{ secrets.GRADLE_ENTERPRISE_KEY }}
          JAVA_VERSION: ${{matrix.jdk-version}}
        run: ./gradlew :plugin:test --continue --tests "com.jetbrains.packagesearch.plugin.tests.end2end.projectservice.GradleProjectTest"
      - name: Upload test result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: testResult-gradle-${{ matrix.os }}-${{ matrix.gradle-version }}
          path: /home/runner/work/package-search-intellij-plugin/package-search-intellij-plugin/plugin/build/testData
  maven:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    name: Maven on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      MAVEN_SPACE_PASSWORD: ${{ secrets.MAVEN_SPACE_PASSWORD }}
      MAVEN_SPACE_USERNAME: ${{ secrets.MAVEN_SPACE_USERNAME }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: gradle/gradle-build-action@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Run Gradle tests
        env:
          KMP: true
          GRADLE_ENTERPRISE_KEY: ${{ secrets.GRADLE_ENTERPRISE_KEY }}
          JAVA_VERSION: ${{matrix.jdk-version}}
        run: ./gradlew :plugin:test --continue --tests "com.jetbrains.packagesearch.plugin.tests.end2end.projectservice.MavenProjectTest"
      - name: Upload test result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: testResult-maven-${{ matrix.os }}-${{ matrix.gradle-version }}
          path: /home/runner/work/package-search-intellij-plugin/package-search-intellij-plugin/plugin/build/testData
  kmp:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        gradle-version: [ '6.9.2', '7.6.4', '8.6' ]
    name: KMP ${{ matrix.gradle-version }}
    runs-on: ${{ matrix.os }}
    env:
      MAVEN_SPACE_PASSWORD: ${{ secrets.MAVEN_SPACE_PASSWORD }}
      MAVEN_SPACE_USERNAME: ${{ secrets.MAVEN_SPACE_USERNAME }}
    outputs:
      result: ${{ steps.final_step.outputs.result }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: gradle/gradle-build-action@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Run tests
        env:
          KMP: true
          GRADLE_VERSION: ${{ matrix.gradle-version }}
          GRADLE_ENTERPRISE_KEY: ${{ secrets.GRADLE_ENTERPRISE_KEY }}
          JAVA_VERSION: ${{matrix.jdk-version}}
        run: ./gradlew :plugin:test --continue --tests "com.jetbrains.packagesearch.plugin.tests.end2end.projectservice.KMPGradleProjectTest"
      - name: Upload test result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: testResult-kmp-gradle-${{ matrix.os }}-${{ matrix.gradle-version }}
          path: /home/runner/work/package-search-intellij-plugin/package-search-intellij-plugin/plugin/build/testData
  version-catalog:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        gradle-version: [ '7.6.4', '8.6' ]
    name: Version Catalog ${{ matrix.gradle-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      MAVEN_SPACE_PASSWORD: ${{ secrets.MAVEN_SPACE_PASSWORD }}
      MAVEN_SPACE_USERNAME: ${{ secrets.MAVEN_SPACE_USERNAME }}
    outputs:
      result: ${{ steps.final_step.outputs.result }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: gradle/gradle-build-action@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Run tests
        env:
          KMP: true
          GRADLE_VERSION: ${{ matrix.gradle-version }}
          GRADLE_ENTERPRISE_KEY: ${{ secrets.GRADLE_ENTERPRISE_KEY }}
          JAVA_VERSION: ${{matrix.jdk-version}}
        run: ./gradlew :plugin:test --continue --tests "com.jetbrains.packagesearch.plugin.tests.end2end.projectservice.CatalogProjectTest"
      - name: Upload test result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: testResult-version-catalog-${{ matrix.os }}-${{ matrix.gradle-version }}
          path: /home/runner/work/package-search-intellij-plugin/package-search-intellij-plugin/plugin/build/testData
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    env:
      MAVEN_SPACE_PASSWORD: ${{ secrets.MAVEN_SPACE_PASSWORD }}
      MAVEN_SPACE_USERNAME: ${{ secrets.MAVEN_SPACE_USERNAME }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: gradle/gradle-build-action@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Run tests
        env:
          GRADLE_ENTERPRISE_KEY: ${{ secrets.GRADLE_ENTERPRISE_KEY }}
        run: ./gradlew :plugin:utils:test
