name: Run E2E tests

on:
  push:
    branches: [ fabrizio.scarponi/e2e-starter ]

jobs:
  run-e2e-tests:
    continue-on-error: true
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        gradle-versions: [ '5.6.4', '6.9.2', '7.6.4', '8.6', 'latest' ]
    name: E2ETest on ${{ matrix.os }} with Gradle ${{ matrix.gradle-versions }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: gradle/gradle-build-action@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle
      - name: Run Gradle tests
        env:
          GRADLE_VERSION: ${{ matrix.gradle-versions }}
          GRADLE_ENTERPRISE_KEY: ${{ secrets.GRADLE_ENTERPRISE_KEY }}
        run: ./gradlew :plugin:test
